# Generated by Django 4.1.5 on 2023-01-14 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(editable=False, max_length=14)),
                ('nome', models.CharField(editable=False, max_length=14)),
                ('sexo', models.CharField(editable=False, max_length=1)),
                ('email', models.CharField(editable=False, max_length=255)),
                ('dataDeNascimento', models.DateField(blank=True, default=False, null=True)),
                ('rendaMensal', models.DecimalField(decimal_places=3, default=False, max_digits=5)),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'Clientes',
            },
        ),
    ]
