# Generated by Django 4.1.5 on 2023-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='nome',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
    ]
