# Generated by Django 4.1.5 on 2023-01-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_clientemodel_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='cpf',
            new_name='cpf_cliente',
        ),
    ]
