# Generated by Django 4.1.5 on 2023-01-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_rename_cpf_clientemodel_cpf_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='cpf_cliente',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='clientemodel',
            old_name='id',
            new_name='id_cliente',
        ),
    ]
