# Generated by Django 4.1.5 on 2023-01-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_rename_cpf_cliente_clientemodel_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='cpf',
            new_name='cpfcliente',
        ),
    ]
