# Generated by Django 4.1.5 on 2023-01-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_rename_cpf_clientemodel_cpfcliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='cpfcliente',
            new_name='cpf',
        ),
    ]
