# Generated by Django 4.1.5 on 2023-01-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_rename_cpfcliente_clientemodel_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='id_cliente',
            new_name='id',
        ),
    ]
