# Generated by Django 4.1.5 on 2023-01-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_rename_id_cliente_clientemodel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientemodel',
            table='clientes',
        ),
    ]
