# Generated by Django 4.1.5 on 2023-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_remove_clientemodel_rendamensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='rendaMensal',
            field=models.DecimalField(decimal_places=1, default=False, max_digits=5),
        ),
    ]
