# Generated by Django 4.1.5 on 2023-01-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_clientemodel_rendamensal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='id',
            new_name='cliente',
        ),
    ]
