# Generated by Django 4.1.5 on 2023-01-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_rename_id_clientemodel_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientemodel',
            old_name='cliente',
            new_name='id',
        ),
    ]
