# Generated by Django 4.1.5 on 2023-01-15 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('susep', models.CharField(max_length=20)),
                ('expiracaoDeVenda', models.DateField(blank=True, default=False, null=True)),
                ('valorMinimoAporteInicial', models.DecimalField(decimal_places=3, default=False, max_digits=5)),
                ('valorMinimoAporteExtra', models.DecimalField(decimal_places=3, default=False, max_digits=5)),
                ('idadeDeEntrada', models.IntegerField(blank=True, default=False, null=True)),
                ('idadeDeSaida', models.IntegerField(blank=True, default=False, null=True)),
                ('carenciaInicialDeResgate', models.IntegerField(blank=True, default=False, null=True)),
                ('carenciaEntreResgates', models.IntegerField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'produtos',
            },
        ),
    ]
