# Generated by Django 4.1.5 on 2023-01-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtomodel',
            name='valorMinimoAporteExtra',
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='valorMinimoAporteInicial',
        ),
    ]
