# Generated by Django 4.1.5 on 2023-01-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produtomodel_valorminimoaporteextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='valorMinimoAporteExtra',
            field=models.DecimalField(decimal_places=1, default=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='valorMinimoAporteInicial',
            field=models.DecimalField(decimal_places=1, default=False, max_digits=10),
        ),
    ]
