# Generated by Django 4.1.5 on 2023-01-17 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0013_rename_cliente_clientemodel_id'),
        ('produto', '0003_produtomodel_valorminimoaporteextra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aporte', models.DecimalField(decimal_places=3, default=False, max_digits=10)),
                ('dataDaContratacao', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='cliente.clientemodel')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produtomodel')),
            ],
            options={
                'verbose_name': 'Plano',
                'db_table': 'plano',
            },
        ),
        migrations.CreateModel(
            name='ResgateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorResgate', models.DecimalField(decimal_places=3, default=False, max_digits=10)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.planomodel')),
            ],
            options={
                'verbose_name': 'Resgate',
                'db_table': 'resgate',
            },
        ),
        migrations.CreateModel(
            name='AporteExtraModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorAporte', models.DecimalField(decimal_places=3, default=False, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.planomodel')),
            ],
            options={
                'verbose_name': 'Aporte_Extra',
                'db_table': 'apoete_extra',
            },
        ),
    ]
