# Generated by Django 4.1.5 on 2023-01-15 23:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0003_produtomodel_valorminimoaporteextra_and_more'),
        ('cliente', '0011_clientemodel_rendamensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte', models.DecimalField(decimal_places=3, default=False, max_digits=10)),
                ('dataDaContratacao', models.DateField(blank=True, default=False, null=True)),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel')),
                ('idProduto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produtomodel')),
            ],
            options={
                'verbose_name': 'Plano',
                'db_table': 'plano',
            },
        ),
        migrations.CreateModel(
            name='ResgateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorResgate', models.DecimalField(decimal_places=3, default=False, max_digits=10)),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.planomodel')),
            ],
            options={
                'verbose_name': 'Resgate',
                'db_table': 'resgate',
            },
        ),
        migrations.CreateModel(
            name='AporteExtraModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorAporte', models.DecimalField(decimal_places=3, default=False, max_digits=10)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.planomodel')),
            ],
            options={
                'verbose_name': 'Aporte_Extra',
                'db_table': 'apoete_extra',
            },
        ),
    ]
