# Generated by Django 4.1.5 on 2023-01-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0002_alter_planomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteextramodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resgatemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
