# Generated by Django 4.1.5 on 2023-01-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0006_alter_planomodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planomodel',
            old_name='idCliente',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='planomodel',
            old_name='idProduto',
            new_name='Produto',
        ),
    ]
