# Generated by Django 4.1.5 on 2023-01-16 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0007_rename_idcliente_planomodel_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aporteextramodel',
            old_name='idCliente',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='aporteextramodel',
            old_name='idPlano',
            new_name='Plano',
        ),
        migrations.RenameField(
            model_name='resgatemodel',
            old_name='idPlano',
            new_name='Plano',
        ),
        migrations.AlterField(
            model_name='aporteextramodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resgatemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
