# Generated by Django 4.1.5 on 2023-01-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_clientemodel_rendamensal'),
        ('produto', '0003_produtomodel_valorminimoaporteextra_and_more'),
        ('plano', '0008_rename_idcliente_aporteextramodel_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planomodel',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='cliente.clientemodel'),
        ),
        migrations.AlterField(
            model_name='planomodel',
            name='Produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produtomodel'),
        ),
    ]
