# Generated by Django 4.1.5 on 2023-01-16 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0010_alter_planomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planomodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
