# Generated by Django 4.1.5 on 2023-01-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0011_alter_planomodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aporteextramodel',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='aporteextramodel',
            old_name='Plano',
            new_name='plano',
        ),
        migrations.RenameField(
            model_name='planomodel',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='planomodel',
            old_name='Produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='resgatemodel',
            old_name='Plano',
            new_name='plano',
        ),
    ]
