# Generated by Django 4.1.5 on 2023-01-16 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0012_rename_cliente_aporteextramodel_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planomodel',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
