# Generated by Django 4.1.5 on 2023-01-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0013_alter_planomodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planomodel',
            name='dataDaContratacao',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
